packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.16.1+sha512-ezIsMs06mTSjPqip8fcXJCx0KXVzRd3vSyjHr2YvTiqksY3Q+l9yd+YZg7Yo4CMwnyndZAolaqXX2WrN0XEWAw==
loglevel: info
minimumReleaseAgeExclude:
  - json-schema-effect@0.2.2
  - "@microsoft/api-extractor@7.58.9"
  - "@rushstack/ts-command-line@5.3.10"
